[project]
name = "post-tagging-model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "nltk>=3.9.1",
    "numpy<2",
    "torch==2.0.1",
    "tqdm>=4.67.1",
]
